### ISSUE TITLE
Suppress Tab Bar Width

### ISSUE THREAD

**Issue by sxandy** [anakinsk/SafariStand#12] opened 2016-10-19 18:15 UTC
Suppress Tab Bar Width not working correct no Label on thirst tab, rearranging tabs also
not working.
Bookmark Icon on Console Panel not visible it is not a big issue 

Thank you for bringing SafariStand to version 10 :)

**Comment by anakinsk** [comment] 2016-10-19 21:47
Hey could you pls derive bookmark icon into a separate issue?

**Comment by crathecrub** [comment] 2016-10-20 08:16
@sxandy Please see https://github.com/anakinsk/SafariStand/issues/5

**Comment by Fofer** [comment] 2016-10-21 15:23
By "bookmark icon" do you mean "favicon?"  Because I am seeing them on the pages listed in my Console Panel.

**Comment by sxandy** [comment] 2016-10-21 20:43
@Fofer I mean the icon in the toolbar it is not visible.

**Comment by anakinsk** [comment] 2017-08-01 08:21
Duplicate of https://github.com/anakinsk/SafariStand/issues/5

**Closed by anakinsk** 2017-08-01 08:21 UTC
