### ISSUE TITLE
When activating option "Hide Title" the Favourites bar doesn't refresh

### ISSUE THREAD

**Issue by ceribbo** [anakinsk/SafariStand#25] opened 2016-12-01 01:43 UTC
When the option "Hide Title" of a Favourite site is activated, the toolbar doesn't change immediately: the title must be renamed or safari must be reopened in order to hide the title.

**Comment by anakinsk** [comment] 2017-08-01 08:41
Duplicate of https://github.com/anakinsk/SafariStand/issues/20

**Closed by anakinsk** 2017-08-01 08:41 UTC
