### ISSUE TITLE
SafariStand 11 crashed Safari 11

### ISSUE THREAD

**Issue by Tinrobotguy** [anakinsk/SafariStand#65] opened 2017-10-31 19:46 UTC
I installed SafariStand 11 and now Safari won't even load.  I am running El Capitan.  Why did it crash Safari and how can I fix this?  Perhaps I didn't install it correctly.  I disabled SIP and installed SIMBL and ran the patch and added SafariStand.bundle to SIMBL, but it didn't work and as I say, worse than that, Safari now won't even run.  I am now using a backup I had, but obviously that doesn't help get SafariStand running.

**Comment by anakinsk** [comment] 2017-11-02 00:47
Hi, take a look at this:

https://github.com/anakinsk/SafariStand/issues/52

Safari Stand currently does not support El Capitan and Safari 11. What you can try is to apply binaries from the post yourself and see if it is working. Or wait until I find some time to resolve this. 

Closing as a duplicate.

**Closed as completed by anakinsk** 2017-11-02 00:47 UTC
Labels: duplicate

**Comment by Tinrobotguy** [comment] 2017-11-02 00:49
Really.  Why is it clearly stated that it does?  Clearly there is something I don't understand about how this works.  https://github.com/anakinsk/SafariStand/releases/tag/11.0.0

**Comment by anakinsk** [comment] 2017-11-02 00:54
The funny thing about all those different OS versions, is that even tho it says that all you guys have Safari 11, in reality what you have on El Capitan is different from what others have on Sierra and High Sierra. So making Stand to support Safari 11 on one OS does not necessarily mean that you get support for the others for free.

Hope that makes sense.

**Comment by Tinrobotguy** [comment] 2017-11-02 00:56
I see.  Okay, so when I get High Sierra, SafariStand will work there, but not in El Cap.  Didn't realize  it was different.  Will it get updated to work with El Cap, or is that old news?  I haven't upgraded because some of my software will not work on High Sierra.

**Comment by anakinsk** [comment] 2017-11-02 01:03
Correct.

Safari Stand support for Safari 11 and El Capitan is considered to be a feature request and scheduled for the next release. There's no ETA for that however as I am quite busy atm. But hopefully it will be delivered within a month. 

According to one of the users report, the only reason it crashes is because the original patcher was designed for Sierra and above, but not for El Capitan. That user even provided the correct binaries. I didn't test them, but they claim it works, so you could try to manually patch your safari if you don't want to wait for the "official" patch :)

However keep in mind that I won't provide any support with this.

**Comment by Tinrobotguy** [comment] 2017-11-02 02:11
Okay thanks.  I am not skilled enough in the ways of binaries to do such things so I will wait for your official supported version.  Thank you.

**Comment by Tinrobotguy** [comment] 2017-11-02 20:59
Hey, I need to ask one thing.  The instructions advise backing up Safari before doing anything.  I dragged copy onto my desktop and then, when it didn't work, wanted to put that copy back, but the system won't let me as I get an error message telling me that Safari cannot be changed because it is required by the OS.  So how does one back up and restore Safari to avoid this?

**Comment by anakinsk** [comment] 2017-11-05 20:52
you probably need to disable system integrity protection before doing it. If that still does not help, doing it via terminal will sure work.

**Comment by Tinrobotguy** [comment] 2017-11-06 19:33
I actually did disable SIP.  Doing it via Terminal is not something I know how to do.  

By the way, on the site here, https://github.com/anakinsk/SafariStand/blob/master/README.md#macos-sierra-10124-and-library-validation,  it says, **"Current version supports Safari 11, 10.1 & 10.0 on Yosemite, El Capitan, Sierra and High Sierra."** but you say here that it does not support Safari 11  and El C.  I'm confused.

**Comment by anakinsk** [comment] 2017-11-06 22:49
"cp" and/or "mv" commands should work via "sudo". You can google them to get more info 😀

Yeah I probably need to invest some time to do some kind of a support table which clearly shows what we support and how. But you see me doing this alone significantly narrows the amount of things I can get done in given amount of time.
