### ISSUE TITLE
Hide Tabbar not working

### ISSUE THREAD

**Issue by daven1985** [anakinsk/SafariStand#33] opened 2017-01-20 03:32 UTC
Afternoon,

When select "Hide tabbar" does nothing. Can this be fixed?

Cheers.

**Comment by daven1985** [comment] 2017-01-22 20:15
Just discovered today, if you hide the sidebar and then re-enable it the tabbar does disappear. However as soon as you open a new tab it re-appears.

Thought it might help!

**Comment by skinetserver** [comment] 2017-02-02 07:08
I am also experiencing this issue. The new tab request seems to be overriding the hide Tabbar.

**Comment by anakinsk** [comment] 2017-08-01 08:44
Duplicate of https://github.com/anakinsk/SafariStand/issues/10

**Closed by anakinsk** 2017-08-01 08:44 UTC
