### ISSUE TITLE
Can you please make this great plugin works on Yosemite with Safari10 as well?

### ISSUE THREAD

**Issue by jasperzs** [anakinsk/SafariStand#14] opened 2016-10-21 18:40 UTC
Hi, I just tried the latest release, but it does not work on Yosemite 10.10.5 with Safari and it raised an error every single time I restart Safari.
<img width="420" alt="screen shot 2016-10-21 at 2 39 11 pm" src="https://cloud.githubusercontent.com/assets/15724519/19608042/5369cac0-979c-11e6-9b75-4207089dd696.png">

**Comment by anakinsk** [comment] 2016-10-23 05:56
Hi, I will close this one as a duplicate of the issue #4 (Can your new fork support Safari 10 on Yosemite?). Thanks for letting me know tho.

**Closed by anakinsk** 2016-10-23 05:56 UTC
